### ISSUE TITLE
Can't Sync RHEL Repo

### ISSUE THREAD

**Issue by admin-pro** [pyther/upstream_sync#9]
Hello Pyher,

I try to follow your procedure from : https://github.com/pyther/upstream_sync

Thank you for your job ! It is a great script.

But actually i don't have success to sync the RHEL repo , the EPEL Repo is OK.

I think that the problem come from the sslkey and sslcert where i can found this please ?

My goal is to sync repo/distrib RHEL 5 , 6 and 7 - EPEL 5, 6 ,7 - CentOS 5 , 6 , 7

I have some clients machine Rhel and Centos.

I want to use a Local repo that sync all of this :) with your awesome script !

Of course i have the license etc... for all RHEL servers.

But i encounter this following error for rhel

I run the following command :

![image](https://cloud.githubusercontent.com/assets/19953088/16085843/bb4edf56-331d-11e6-8ac3-0e7829dae0b6.png)

Here is my configuration :

the auth file :
etc_auth
![image](https://cloud.githubusercontent.com/assets/19953088/16085861/ca91c4ce-331d-11e6-97ce-9be1f6b73a6d.png)

The script is here : 
/root/upstream_sync-master/

The variable in the script : 
mirror_dir = '/var/ftp/pub'
confd_dir = '/etc/upstream_sync/'

The redhat repo : 
i use your example in the readme

Thank you

Regards

Pierre

**Comment by admin-pro** [comment]
Hello have any idea ?

thank you very much

**Comment by ahmedsajid** [comment]
@admin-pro did you find solution to this? I'm having the same issue.

**Comment by pyther** [comment]
I would try debugging this with curl. The CDN server likely doesn't like your SSL Client certificates.

**Comment by ahmedsajid** [comment]
Thanks @pyther 
I was able to figure out the issue. I made a mistake while copying the URL.
